// <auto-generated />
using System;
using Assignment2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment2.Migrations
{
    [DbContext(typeof(LOContext))]
    [Migration("20190927172147_metric")]
    partial class metric
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("department");

                    b.Property<string>("description");

                    b.Property<int>("metricPercent");

                    b.Property<string>("name");

                    b.Property<int>("number");

                    b.Property<string>("professor");

                    b.Property<string>("professorEmail");

                    b.Property<string>("semeseter");

                    b.Property<int>("year");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Assignment2.Models.LearningOutcome", b =>
                {
                    b.Property<int>("LearningOutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseNum");

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<int?>("number");

                    b.HasKey("LearningOutcomeId");

                    b.HasIndex("number");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("Assignment2.Models.LearningOutcome", b =>
                {
                    b.HasOne("Assignment2.Models.Course", "Course")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("number");
                });
#pragma warning restore 612, 618
        }
    }
}
